// Central skill ontology. Each entry: { display, aliases }.
// aliases — lowercase strings that map to the canonical display name.
// Used for: dep matching, topic matching, README/description text matching, badge alt text.

const SKILL_ONTOLOGY = {
  languages: [
    { display: "JavaScript", aliases: ["javascript", "js"] },
    { display: "TypeScript", aliases: ["typescript", "ts"] },
    { display: "Python",     aliases: ["python", "py"] },
    { display: "Java",       aliases: ["java"] },
    { display: "C++",        aliases: ["c++", "cpp", "cplusplus", "c-plus-plus"] },
    { display: "C#",         aliases: ["c#", "csharp", "c-sharp"] },
    { display: "Go",         aliases: ["golang"] },
    { display: "Rust",       aliases: ["rust"] },
    { display: "Kotlin",     aliases: ["kotlin"] },
    { display: "Swift",      aliases: ["swift"] },
    { display: "Dart",       aliases: ["dart"] },
    { display: "Ruby",       aliases: ["ruby"] },
    { display: "PHP",        aliases: ["php"] },
    { display: "Scala",      aliases: ["scala"] },
    { display: "Elixir",     aliases: ["elixir"] },
    { display: "Haskell",    aliases: ["haskell"] },
    { display: "Shell",      aliases: ["shell", "bash", "zsh"] },
    { display: "R",          aliases: ["r-language"] },
    { display: "C",          aliases: ["c-language"] },
  ],

  frameworks: [
    { display: "React",           aliases: ["react", "reactjs", "react.js", "react-js"] },
    { display: "Next.js",         aliases: ["next", "nextjs", "next.js", "next-js"] },
    { display: "Vue",             aliases: ["vue", "vuejs", "vue.js", "vue-js"] },
    { display: "Nuxt",            aliases: ["nuxt", "nuxtjs", "nuxt.js"] },
    { display: "Angular",         aliases: ["angular", "angularjs"] },
    { display: "Svelte",          aliases: ["svelte"] },
    { display: "SvelteKit",       aliases: ["sveltekit"] },
    { display: "Astro",           aliases: ["astro"] },
    { display: "Remix",           aliases: ["remix"] },
    { display: "Express",         aliases: ["express", "expressjs", "express.js"] },
    { display: "Fastify",         aliases: ["fastify"] },
    { display: "NestJS",          aliases: ["nestjs", "nest"] },
    { display: "Koa",             aliases: ["koa"] },
    { display: "Hono",            aliases: ["hono"] },
    { display: "FastAPI",         aliases: ["fastapi", "fast-api", "fast api"] },
    { display: "Flask",           aliases: ["flask"] },
    { display: "Django",          aliases: ["django"] },
    { display: "Starlette",       aliases: ["starlette"] },
    { display: "aiohttp",         aliases: ["aiohttp"] },
    { display: "Rails",           aliases: ["rails", "ruby-on-rails", "ruby on rails", "ror"] },
    { display: "Laravel",         aliases: ["laravel"] },
    { display: "Spring Boot",     aliases: ["spring-boot", "springboot", "spring boot"] },
    { display: "Spring Security", aliases: ["spring-security", "spring security"] },
    { display: "Gin",             aliases: ["gin"] },
    { display: "Fiber",           aliases: ["fiber"] },
    { display: "Axum",            aliases: ["axum"] },
    { display: "Rocket",          aliases: ["rocket"] },
    { display: "Actix-web",       aliases: ["actix-web", "actix web"] },
    { display: "Flutter",         aliases: ["flutter"] },
    { display: "React Native",    aliases: ["react-native", "react native", "reactnative"] },
    { display: "Expo",            aliases: ["expo"] },
    { display: "Node.js",         aliases: ["nodejs", "node.js", "node-js"] },
  ],

  libraries: [
    // ML / Data Science
    { display: "PyTorch",         aliases: ["pytorch", "torch"] },
    { display: "TensorFlow",      aliases: ["tensorflow", "tf"] },
    { display: "Keras",           aliases: ["keras"] },
    { display: "XGBoost",         aliases: ["xgboost"] },
    { display: "LightGBM",        aliases: ["lightgbm"] },
    { display: "OpenCV",          aliases: ["opencv", "cv2"] },
    // Computer Vision models & tools
    { display: "YOLOv8",          aliases: ["yolov8", "yolov5", "yolo", "ultralytics"] },
    { display: "ResNet",          aliases: ["resnet", "resnet50", "resnet101", "resnet152"] },
    { display: "ViT",             aliases: ["vit", "vision transformer", "vision-transformer"] },
    { display: "CLIP",            aliases: ["clip", "openai clip"] },
    { display: "FaceNet",         aliases: ["facenet"] },
    { display: "MediaPipe",       aliases: ["mediapipe", "media pipe"] },
    { display: "Albumentations",  aliases: ["albumentations"] },
    { display: "TorchVision",     aliases: ["torchvision", "torch vision"] },
    { display: "Detectron2",      aliases: ["detectron2", "detectron"] },
    { display: "dlib",            aliases: ["dlib"] },
    // NLP
    { display: "BERT",            aliases: ["bert", "roberta", "distilbert", "albert"] },
    { display: "spaCy",           aliases: ["spacy"] },
    { display: "NLTK",            aliases: ["nltk", "natural language toolkit"] },
    // Generative / Diffusion
    { display: "Stable Diffusion",aliases: ["stable diffusion", "stablediffusion", "stable-diffusion", "sdxl", "sd-xl"] },
    // Experiment tracking
    { display: "Weights & Biases",aliases: ["weights & biases", "wandb", "w&b", "weights and biases"] },
    { display: "Transformers",    aliases: ["transformers"] },
    { display: "Diffusers",       aliases: ["diffusers"] },
    { display: "JAX",             aliases: ["jax"] },
    { display: "NumPy",           aliases: ["numpy", "np"] },
    { display: "Pandas",          aliases: ["pandas", "pd"] },
    { display: "Matplotlib",      aliases: ["matplotlib"] },
    { display: "Seaborn",         aliases: ["seaborn"] },
    { display: "Plotly",          aliases: ["plotly"] },
    { display: "SciPy",           aliases: ["scipy"] },
    { display: "scikit-learn",    aliases: ["scikit-learn", "sklearn", "scikit learn"] },
    // LLM / Agents
    { display: "LangChain",       aliases: ["langchain", "lang-chain"] },
    { display: "LangGraph",       aliases: ["langgraph"] },
    { display: "LlamaIndex",      aliases: ["llama-index", "llama index", "llamaindex"] },
    { display: "Hugging Face",    aliases: ["hugging-face", "hugging face", "huggingface", "huggingface-hub"] },
    { display: "OpenAI SDK",      aliases: ["openai"] },
    { display: "Anthropic SDK",   aliases: ["anthropic"] },
    { display: "Gemini",          aliases: ["gemini", "gemini-api", "google-generativeai"] },
    { display: "Groq",            aliases: ["groq"] },
    { display: "Cohere",          aliases: ["cohere"] },
    { display: "MistralAI",       aliases: ["mistralai"] },
    { display: "CrewAI",          aliases: ["crewai"] },
    { display: "AutoGen",         aliases: ["autogen", "pyautogen", "autogen-agentchat", "microsoft-autogen", "ag2"] },
    { display: "smolagents",      aliases: ["smolagents"] },
    { display: "Agno",            aliases: ["agno"] },
    { display: "ADK",             aliases: ["adk", "google-adk", "google adk", "agent development kit", "google-generativeai-adk"] },
    { display: "MCP",             aliases: ["mcp", "model-context-protocol", "model context protocol", "modelcontextprotocol"] },
    { display: "Pydantic AI",     aliases: ["pydantic-ai", "pydantic ai", "pydanticai"] },
    { display: "Tambo",           aliases: ["tambo", "@tambo-ai/react", "tambo-ai"] },
    { display: "Parlant",         aliases: ["parlant"] },
    { display: "Pipecat",         aliases: ["pipecat", "pipecat-ai"] },
    { display: "LiveKit",         aliases: ["livekit", "livekit-agents", "livekit-server-sdk"] },
    { display: "Deepgram",        aliases: ["deepgram", "deepgram-sdk"] },
    { display: "Firecrawl",       aliases: ["firecrawl", "firecrawl-py", "@mendable/firecrawl-js"] },
    { display: "E2B",             aliases: ["e2b", "e2b-code-interpreter"] },
    // AI / GenAI — fine-tuning & serving
    { display: "vLLM",                aliases: ["vllm"] },
    { display: "PEFT",                aliases: ["peft", "lora", "qlora", "loralib"] },
    { display: "SentenceTransformers",aliases: ["sentence-transformers", "sentence transformers", "sentencetransformers"] },
    { display: "Haystack",            aliases: ["haystack", "haystack-ai", "deepset-haystack"] },
    { display: "DSPy",                aliases: ["dspy"] },
    { display: "Semantic Kernel",     aliases: ["semantic-kernel", "semantic kernel"] },
    { display: "RAG",                 aliases: ["rag", "retrieval-augmented-generation", "retrieval augmented generation"] },
    { display: "Multi-Agent Systems", aliases: ["multi-agent-systems", "multi agent systems", "multi-agent"] },
    { display: "Tool Calling",        aliases: ["tool-calling", "tool calling", "function-calling", "function calling"] },
    { display: "Agent Orchestration", aliases: ["agent-orchestration", "agent orchestration", "orchestration"] },
    { display: "Semantic Search",     aliases: ["semantic-search", "semantic search"] },
    { display: "Context Engineering", aliases: ["context-engineering", "context engineering"] },
    { display: "Vector Search",       aliases: ["vector-search", "vector search"] },
    { display: "Knowledge Graphs",    aliases: ["knowledge-graph", "knowledge graphs", "graph-rag", "graphrag"] },
    // MLOps
    { display: "MLflow",          aliases: ["mlflow"] },
    { display: "BentoML",         aliases: ["bentoml"] },
    { display: "Airflow",         aliases: ["airflow"] },
    { display: "Prefect",         aliases: ["prefect"] },
    { display: "DVC",             aliases: ["dvc"] },
    { display: "Ray",             aliases: ["ray"] },
    // Data Engineering
    { display: "PySpark",         aliases: ["pyspark", "spark", "apache-spark", "apache spark"] },
    { display: "dbt",             aliases: ["dbt", "dbt-core"] },
    { display: "Flink",           aliases: ["flink", "apache-flink", "apache flink"] },
    // Backend / Infra
    { display: "gRPC",            aliases: ["grpc", "grpcio"] },
    { display: "Kafka",           aliases: ["kafka", "confluent-kafka", "kafka-python"] },
    { display: "RabbitMQ",        aliases: ["rabbitmq", "pika", "amqp"] },
    // Frontend
    { display: "Tailwind CSS",    aliases: ["tailwindcss", "tailwind", "tailwind-css", "tailwind css"] },
    { display: "Redux",           aliases: ["redux"] },
    { display: "Zustand",         aliases: ["zustand"] },
    { display: "Axios",           aliases: ["axios"] },
    { display: "GraphQL",         aliases: ["graphql"] },
    { display: "tRPC",            aliases: ["trpc"] },
    { display: "Three.js",        aliases: ["three", "threejs", "three.js"] },
    { display: "D3.js",           aliases: ["d3", "d3js", "d3.js"] },
    { display: "Framer Motion",   aliases: ["framer-motion", "framer motion"] },
    { display: "Socket.io",       aliases: ["socket-io", "socket.io", "socketio", "socket io"] },
    { display: "React Query",     aliases: ["react-query", "react query", "@tanstack/react-query"] },
    // ORM / Query builders
    { display: "Prisma",          aliases: ["prisma"] },
    { display: "TypeORM",         aliases: ["typeorm"] },
    { display: "Sequelize",       aliases: ["sequelize"] },
    { display: "SQLAlchemy",      aliases: ["sqlalchemy"] },
    { display: "Hibernate",       aliases: ["hibernate"] },
    { display: "Drizzle",         aliases: ["drizzle"] },
    { display: "Mongoose",        aliases: ["mongoose"] },
  ],

  databases: [
    { display: "MongoDB",         aliases: ["mongodb", "mongo", "pymongo"] },
    { display: "PostgreSQL",      aliases: ["postgresql", "postgres", "pg", "psycopg2", "psycopg"] },
    { display: "MySQL",           aliases: ["mysql", "mysql2"] },
    { display: "SQLite",          aliases: ["sqlite", "sqlite3"] },
    { display: "Redis",           aliases: ["redis", "ioredis"] },
    { display: "Firebase",        aliases: ["firebase"] },
    { display: "Supabase",        aliases: ["supabase"] },
    { display: "Pinecone",        aliases: ["pinecone"] },
    { display: "Weaviate",        aliases: ["weaviate"] },
    { display: "Neo4j",           aliases: ["neo4j"] },
    { display: "Cassandra",       aliases: ["cassandra"] },
    { display: "Qdrant",          aliases: ["qdrant", "qdrant-client", "qdrant client"] },
    { display: "ChromaDB",        aliases: ["chromadb", "chroma-db", "chroma db", "chromadb-client"] },
    { display: "FAISS",           aliases: ["faiss", "faiss-cpu", "faiss-gpu"] },
    { display: "DynamoDB",        aliases: ["dynamodb"] },
    { display: "Elasticsearch",   aliases: ["elasticsearch", "elastic"] },
    { display: "Neon",            aliases: ["neondb", "neon"] },
    { display: "PlanetScale",     aliases: ["planetscale"] },
    { display: "Snowflake",       aliases: ["snowflake"] },
    { display: "Databricks",      aliases: ["databricks"] },
    { display: "Hive",            aliases: ["hive", "apache-hive", "apache hive"] },
    { display: "ClickHouse",      aliases: ["clickhouse"] },
    { display: "Airbyte",         aliases: ["airbyte"] },
  ],

  tools: [
    // Real-time / streaming protocols
    { display: "WebRTC",          aliases: ["webrtc", "web-rtc"] },
    { display: "WebSockets",      aliases: ["websocket", "websockets", "ws", "socket", "websocket server"] },
    { display: "Speech-to-Text",  aliases: ["speech-to-text", "speech to text", "stt", "transcription", "whisper"] },
    // API paradigms
    { display: "REST API",        aliases: [
        "rest api", "rest_api", "rest-api", "restapi",
        "restful api", "restful-api", "restful_api",
        "rest", "restful",
        "api development", "backend api", "web api", "http api",
        "http rest", "json api", "json rest",
    ]},
    // DevTools / IDEs / Design
    { display: "Git",             aliases: ["git"] },
    { display: "GitHub",          aliases: ["github"] },
    { display: "GitLab",          aliases: ["gitlab"] },
    { display: "Linux",           aliases: ["linux", "ubuntu", "debian", "centos", "arch linux"] },
    { display: "Bash",            aliases: ["bash"] },
    { display: "VSCode",          aliases: ["vscode", "visual studio code", "vs code"] },
    { display: "Postman",         aliases: ["postman"] },
    { display: "Figma",           aliases: ["figma"] },
    { display: "Android Studio",  aliases: ["android studio", "android-studio"] },
    { display: "Xcode",           aliases: ["xcode"] },
    // Container / Infra
    { display: "Docker",          aliases: ["docker"] },
    { display: "Kubernetes",      aliases: ["kubernetes", "k8s"] },
    { display: "Terraform",       aliases: ["terraform"] },
    { display: "Ansible",         aliases: ["ansible"] },
    { display: "Nginx",           aliases: ["nginx"] },
    { display: "Traefik",         aliases: ["traefik"] },
    { display: "Consul",          aliases: ["consul", "hashicorp-consul"] },
    { display: "Vault",           aliases: ["vault", "hashicorp-vault"] },
    { display: "ZooKeeper",       aliases: ["zookeeper", "apache-zookeeper"] },
    // CI / CD
    { display: "GitHub Actions",  aliases: ["github-actions", "github actions"] },
    { display: "Jenkins",         aliases: ["jenkins"] },
    { display: "CircleCI",        aliases: ["circleci"] },
    // Cloud
    { display: "AWS",             aliases: ["aws", "amazon web services"] },
    { display: "GCP",             aliases: ["gcp", "google cloud", "google-cloud"] },
    { display: "Azure",           aliases: ["azure", "microsoft azure"] },
    { display: "Vercel",          aliases: ["vercel"] },
    { display: "Netlify",         aliases: ["netlify"] },
    { display: "Heroku",          aliases: ["heroku"] },
    { display: "Render",          aliases: ["render"] },
    { display: "Railway",         aliases: ["railway"] },
    { display: "Cloudflare",      aliases: ["cloudflare"] },
    { display: "DigitalOcean",    aliases: ["digitalocean", "digital ocean"] },
    { display: "Fly.io",          aliases: ["fly.io", "flyio"] },
    { display: "Ollama",          aliases: ["ollama"] },
    // Build tools
    { display: "Vite",            aliases: ["vite"] },
    { display: "Webpack",         aliases: ["webpack"] },
    { display: "Maven",           aliases: ["maven"] },
    { display: "Gradle",          aliases: ["gradle"] },
    // Monitoring
    { display: "Prometheus",      aliases: ["prometheus"] },
    { display: "Grafana",         aliases: ["grafana"] },
    // Cybersecurity
    { display: "Burp Suite",      aliases: ["burpsuite", "burp suite", "burp-suite"] },
    { display: "Metasploit",      aliases: ["metasploit", "msfconsole"] },
    { display: "Wireshark",       aliases: ["wireshark"] },
    { display: "Nmap",            aliases: ["nmap"] },
    { display: "Kali Linux",      aliases: ["kali", "kali linux", "kali-linux"] },
    // Testing
    { display: "Jest",            aliases: ["jest"] },
    { display: "Pytest",          aliases: ["pytest"] },
    { display: "Vitest",          aliases: ["vitest"] },
    { display: "JUnit",           aliases: ["junit"] },
    { display: "Playwright",      aliases: ["playwright"] },
    { display: "Cypress",         aliases: ["cypress"] },
  ],
};

// ── Build lookup maps ─────────────────────────────────────────────────────────

const ALIAS_TO_DISPLAY  = new Map();
const ALIAS_TO_CATEGORY = new Map();

for (const [category, skills] of Object.entries(SKILL_ONTOLOGY)) {
  for (const { display, aliases } of skills) {
    // The display name itself is always a valid alias
    ALIAS_TO_DISPLAY.set(display.toLowerCase(), display);
    ALIAS_TO_CATEGORY.set(display, category);
    for (const alias of aliases) {
      ALIAS_TO_DISPLAY.set(alias.toLowerCase(), display);
      ALIAS_TO_CATEGORY.set(alias.toLowerCase(), category);
    }
  }
}

// ── normalizeSkillName ────────────────────────────────────────────────────────

function normalizeSkillName(raw) {
  if (!raw) return null;
  return ALIAS_TO_DISPLAY.get(raw.toLowerCase().trim()) || null;
}

// ── TEXT_KEYWORDS ─────────────────────────────────────────────────────────────
// Pre-vetted alias → display pairs safe for word-boundary / substring matching
// in free-form prose (README text, repo descriptions).
// Multi-word entries → substring match. Single-word → word-boundary match.
// Excluded: ambiguous single chars / common words ("go", "r", "c", bare "next", "node").
// "golang" / "nodejs" etc. are used instead of bare "go" / "node".

const TEXT_KEYWORDS = [
  // Languages (safe for text matching — long / distinctive enough)
  ["javascript",      "JavaScript"],
  ["typescript",      "TypeScript"],
  ["python",          "Python"],
  ["golang",          "Go"],       // "go" alone is ambiguous; "golang" is not
  ["java",            "Java"],
  ["kotlin",          "Kotlin"],
  ["swift",           "Swift"],
  ["dart",            "Dart"],
  ["rust",            "Rust"],
  ["ruby",            "Ruby"],
  ["php",             "PHP"],
  ["scala",           "Scala"],
  ["elixir",          "Elixir"],
  ["haskell",         "Haskell"],
  ["flutter",         "Flutter"],  // framework, but commonly appears in language lists
  // Frameworks
  ["react",           "React"],
  ["reactjs",         "React"],
  ["react.js",        "React"],
  ["angular",         "Angular"],
  ["svelte",          "Svelte"],
  ["sveltekit",       "SvelteKit"],
  ["django",          "Django"],
  ["flask",           "Flask"],
  ["fastapi",         "FastAPI"],
  ["nextjs",          "Next.js"],
  ["next.js",         "Next.js"],
  ["vuejs",           "Vue"],
  ["vue.js",          "Vue"],
  ["spring boot",     "Spring Boot"],
  ["react native",    "React Native"],
  ["node.js",         "Node.js"],
  ["nodejs",          "Node.js"],
  // Libraries
  ["pytorch",         "PyTorch"],
  ["tensorflow",      "TensorFlow"],
  ["scikit-learn",    "scikit-learn"],
  ["sklearn",         "scikit-learn"],
  // CV models
  ["yolov8",          "YOLOv8"],
  ["yolov5",          "YOLOv8"],
  ["yolo",            "YOLOv8"],
  ["ultralytics",     "YOLOv8"],
  ["resnet",          "ResNet"],
  ["vit",             "ViT"],
  ["vision transformer", "ViT"],
  ["clip",            "CLIP"],
  ["facenet",         "FaceNet"],
  ["mediapipe",       "MediaPipe"],
  ["media pipe",      "MediaPipe"],
  ["albumentations",  "Albumentations"],
  ["torchvision",     "TorchVision"],
  ["detectron2",      "Detectron2"],
  ["dlib",            "dlib"],
  // NLP
  ["bert",            "BERT"],
  ["roberta",         "BERT"],
  ["distilbert",      "BERT"],
  ["spacy",           "spaCy"],
  ["nltk",            "NLTK"],
  // GenAI / Diffusion
  ["stable diffusion","Stable Diffusion"],
  ["stable-diffusion","Stable Diffusion"],
  ["sdxl",            "Stable Diffusion"],
  // Experiment tracking
  ["wandb",           "Weights & Biases"],
  ["weights & biases","Weights & Biases"],
  ["weights and biases","Weights & Biases"],
  ["langchain",       "LangChain"],
  ["langgraph",       "LangGraph"],
  ["crewai",          "CrewAI"],
  ["crew ai",         "CrewAI"],
  ["autogen",         "AutoGen"],
  ["pyautogen",       "AutoGen"],
  ["autogen-agentchat","AutoGen"],
  ["pydantic ai",     "Pydantic AI"],
  ["pydantic-ai",     "Pydantic AI"],
  ["pydanticai",      "Pydantic AI"],
  ["agno",            "Agno"],
  ["smolagents",      "smolagents"],
  ["smol agents",     "smolagents"],
  ["openai",          "OpenAI SDK"],
  ["openai sdk",      "OpenAI SDK"],
  ["anthropic",       "Anthropic SDK"],
  ["anthropic sdk",   "Anthropic SDK"],
  ["adk",             "ADK"],
  ["google adk",      "ADK"],
  ["agent development kit", "ADK"],
  ["tailwindcss",     "Tailwind CSS"],
  ["tailwind css",    "Tailwind CSS"],
  ["graphql",         "GraphQL"],
  ["hugging face",    "Hugging Face"],
  ["huggingface",     "Hugging Face"],
  // Databases
  ["mongodb",         "MongoDB"],
  ["postgresql",      "PostgreSQL"],
  ["postgres",        "PostgreSQL"],
  ["mysql",           "MySQL"],
  ["sqlite",          "SQLite"],
  ["redis",           "Redis"],
  ["firebase",        "Firebase"],
  ["supabase",        "Supabase"],
  // Tools / DevTools
  ["docker",          "Docker"],
  ["kubernetes",      "Kubernetes"],
  ["terraform",       "Terraform"],
  ["linux",           "Linux"],
  ["ubuntu",          "Linux"],
  ["figma",           "Figma"],
  ["postman",         "Postman"],
  ["vscode",          "VSCode"],
  ["visual studio code", "VSCode"],
  ["android studio",  "Android Studio"],
  ["github actions",  "GitHub Actions"],
  ["ollama",          "Ollama"],
  // AI / GenAI additions
  ["vllm",                "vLLM"],
  ["peft",                "PEFT"],
  ["lora",                "PEFT"],
  ["qlora",               "PEFT"],
  ["sentence-transformers","SentenceTransformers"],
  ["sentence transformers","SentenceTransformers"],
  ["haystack",            "Haystack"],
  ["dspy",                "DSPy"],
  ["semantic kernel",     "Semantic Kernel"],
  // Data Engineering
  ["pyspark",             "PySpark"],
  ["apache spark",        "PySpark"],
  ["databricks",          "Databricks"],
  ["snowflake",           "Snowflake"],
  ["clickhouse",          "ClickHouse"],
  ["airbyte",             "Airbyte"],
  ["apache flink",        "Flink"],
  // REST API — all surface forms → single canonical token
  ["rest api",            "REST API"],
  ["restful api",         "REST API"],
  ["rest-api",            "REST API"],
  ["restapi",             "REST API"],
  ["restful-api",         "REST API"],
  ["restful_api",         "REST API"],
  ["rest_api",            "REST API"],
  ["restful",             "REST API"],
  ["json api",            "REST API"],
  ["http api",            "REST API"],
  ["api development",     "REST API"],
  ["backend api",         "REST API"],
  // Backend / Infra
  ["kafka",               "Kafka"],
  ["rabbitmq",            "RabbitMQ"],
  ["grpc",                "gRPC"],
  ["traefik",             "Traefik"],
  ["consul",              "Consul"],
  ["zookeeper",           "ZooKeeper"],
  // Cybersecurity
  ["burp suite",          "Burp Suite"],
  ["metasploit",          "Metasploit"],
  ["wireshark",           "Wireshark"],
  ["nmap",                "Nmap"],
  ["kali linux",          "Kali Linux"],
  // Cloud
  ["vercel",          "Vercel"],
  ["netlify",         "Netlify"],
  ["heroku",          "Heroku"],
  ["cloudflare",      "Cloudflare"],
  ["digitalocean",    "DigitalOcean"],
  ["aws",             "AWS"],
  ["azure",           "Azure"],
  ["google cloud",    "GCP"],
  ["gcp",             "GCP"],
];

module.exports = { SKILL_ONTOLOGY, ALIAS_TO_DISPLAY, ALIAS_TO_CATEGORY, normalizeSkillName, TEXT_KEYWORDS };
