export const DOMAIN_CONFIG = {
  ai_ml: {
    label: "Machine Learning",
    description: "Applies classical and deep learning to real problems — model training, computer vision, and end-to-end ML pipelines from data to inference.",
    borderL: "border-l-indigo-500",
    textColor: "text-indigo-400",
    tagBg: "bg-indigo-500/10",
    tagText: "text-indigo-400",
    tagBorder: "border-indigo-500/20",
    dotColor: "bg-indigo-500",
    skills: ["pytorch", "tensorflow", "scikit-learn", "opencv", "hugging face", "numpy", "transformers", "sentencetransformers", "matplotlib"],
  },
  agentic_ai: {
    label: "Agentic AI",
    description: "Builds autonomous agent systems with multi-step reasoning, tool use, and orchestration across LLM-driven workflows.",
    borderL: "border-l-violet-500",
    textColor: "text-violet-400",
    tagBg: "bg-violet-500/10",
    tagText: "text-violet-400",
    tagBorder: "border-violet-500/20",
    dotColor: "bg-violet-500",
    skills: ["mcp", "langgraph", "langchain", "agent orchestration", "multi-agent systems", "agno", "pipecat", "e2b", "firecrawl"],
  },
  genai: {
    label: "Generative AI",
    description: "Works with LLMs, RAG pipelines, and vector retrieval — integrating foundation models into production-grade applications.",
    borderL: "border-l-purple-500",
    textColor: "text-purple-400",
    tagBg: "bg-purple-500/10",
    tagText: "text-purple-400",
    tagBorder: "border-purple-500/20",
    dotColor: "bg-purple-500",
    skills: ["rag", "vllm", "gemini", "openai sdk", "anthropic sdk", "groq", "ollama", "vector search", "semantic search"],
  },
  frontend: {
    label: "Frontend",
    description: "Builds user interfaces and interaction systems — from component architecture to animation, state management, and web performance.",
    borderL: "border-l-sky-500",
    textColor: "text-sky-400",
    tagBg: "bg-sky-500/10",
    tagText: "text-sky-400",
    tagBorder: "border-sky-500/20",
    dotColor: "bg-sky-500",
    skills: ["react", "next.js", "tailwind css", "framer motion", "zustand", "react query", "typescript", "vite"],
  },
  backend: {
    label: "Backend",
    description: "Focuses on scalable API systems, service orchestration, and low-latency server infrastructure across REST, WebSocket, and database layers.",
    borderL: "border-l-emerald-500",
    textColor: "text-emerald-400",
    tagBg: "bg-emerald-500/10",
    tagText: "text-emerald-400",
    tagBorder: "border-emerald-500/20",
    dotColor: "bg-emerald-500",
    skills: ["fastapi", "flask", "rest api", "grpc", "sqlalchemy", "aiohttp", "starlette", "websockets"],
  },
  distributed_systems: {
    label: "Distributed Systems",
    description: "Designs fault-tolerant, horizontally scalable systems — consensus, partitioning, and coordination across distributed infrastructure.",
    borderL: "border-l-blue-500",
    textColor: "text-blue-400",
    tagBg: "bg-blue-500/10",
    tagText: "text-blue-400",
    tagBorder: "border-blue-500/20",
    dotColor: "bg-blue-500",
    skills: ["kubernetes", "docker", "redis", "grpc", "websockets", "postgresql"],
  },
  devops: {
    label: "DevOps",
    description: "Operates CI/CD pipelines, container infrastructure, and cloud deployment workflows with a focus on reliability and automation.",
    borderL: "border-l-orange-500",
    textColor: "text-orange-400",
    tagBg: "bg-orange-500/10",
    tagText: "text-orange-400",
    tagBorder: "border-orange-500/20",
    dotColor: "bg-orange-500",
    skills: ["docker", "kubernetes", "github", "aws", "gcp", "azure", "vercel", "prometheus", "grafana"],
  },
  cybersecurity: {
    label: "Cybersecurity",
    description: "Explores threat modeling, vulnerability analysis, and secure system design across application and infrastructure layers.",
    borderL: "border-l-rose-500",
    textColor: "text-rose-400",
    tagBg: "bg-rose-500/10",
    tagText: "text-rose-400",
    tagBorder: "border-rose-500/20",
    dotColor: "bg-rose-500",
    skills: ["python", "fastapi", "langgraph", "rag", "static analysis"],
  },
  data_science: {
    label: "Data Science",
    description: "Extracts insight from data through statistical modeling, visualization, and analytical pipelines built for real-world decisions.",
    borderL: "border-l-teal-500",
    textColor: "text-teal-400",
    tagBg: "bg-teal-500/10",
    tagText: "text-teal-400",
    tagBorder: "border-teal-500/20",
    dotColor: "bg-teal-500",
    skills: ["pandas", "numpy", "matplotlib", "seaborn", "plotly", "scipy", "scikit-learn"],
  },
  mlops: {
    label: "MLOps",
    description: "Bridges ML research and production — model serving, experiment tracking, and infrastructure for repeatable, observable deployments.",
    borderL: "border-l-amber-500",
    textColor: "text-amber-400",
    tagBg: "bg-amber-500/10",
    tagText: "text-amber-400",
    tagBorder: "border-amber-500/20",
    dotColor: "bg-amber-500",
    skills: ["docker", "kubernetes", "prometheus", "grafana", "vllm", "ollama"],
  },
  algorithms: {
    label: "Algorithms",
    description: "Solves computational problems with rigorous analysis — optimization, data structures, and complexity-aware implementation.",
    borderL: "border-l-lime-500",
    textColor: "text-lime-400",
    tagBg: "bg-lime-500/10",
    tagText: "text-lime-400",
    tagBorder: "border-lime-500/20",
    dotColor: "bg-lime-500",
    skills: ["python", "c++", "c", "java", "r"],
  },
  blockchain: {
    label: "Blockchain",
    description: "Builds decentralized protocols, smart contracts, and Web3 application layers on trustless infrastructure.",
    borderL: "border-l-yellow-500",
    textColor: "text-yellow-400",
    tagBg: "bg-yellow-500/10",
    tagText: "text-yellow-400",
    tagBorder: "border-yellow-500/20",
    dotColor: "bg-yellow-500",
    skills: ["typescript", "javascript", "react", "next.js", "fastapi"],
  },
  embedded: {
    label: "Embedded Systems",
    description: "Programs close to the hardware — firmware, RTOS, sensor integration, and constrained resource environments.",
    borderL: "border-l-stone-400",
    textColor: "text-stone-400",
    tagBg: "bg-stone-500/10",
    tagText: "text-stone-400",
    tagBorder: "border-stone-500/20",
    dotColor: "bg-stone-400",
    skills: ["c", "c++", "assembly", "python", "matlab"],
  },
  networking: {
    label: "Networking",
    description: "Implements protocol design and network programming — from socket-level systems to distributed communications infrastructure.",
    borderL: "border-l-cyan-500",
    textColor: "text-cyan-400",
    tagBg: "bg-cyan-500/10",
    tagText: "text-cyan-400",
    tagBorder: "border-cyan-500/20",
    dotColor: "bg-cyan-500",
    skills: ["go", "c", "python", "websockets", "grpc"],
  },
  database: {
    label: "Databases",
    description: "Designs schema, optimizes queries, and selects storage engines for performance, durability, and correctness under load.",
    borderL: "border-l-green-500",
    textColor: "text-green-400",
    tagBg: "bg-green-500/10",
    tagText: "text-green-400",
    tagBorder: "border-green-500/20",
    dotColor: "bg-green-500",
    skills: ["postgresql", "mysql", "redis", "firebase", "neo4j", "sqlite"],
  },
  systems: {
    label: "Systems",
    description: "Works at the OS and runtime level — memory management, concurrency primitives, and low-level performance engineering.",
    borderL: "border-l-slate-400",
    textColor: "text-slate-300",
    tagBg: "bg-slate-500/10",
    tagText: "text-slate-400",
    tagBorder: "border-slate-500/20",
    dotColor: "bg-slate-400",
    skills: ["c", "c++", "go", "assembly", "shell"],
  },
};

export function getDomainConfig(domain) {
  return (
    DOMAIN_CONFIG[domain] || {
      label: domain,
      description: "Technical domain expertise.",
      borderL: "border-l-zinc-600",
      textColor: "text-zinc-400",
      tagBg: "bg-zinc-800",
      tagText: "text-zinc-400",
      tagBorder: "border-zinc-700",
      dotColor: "bg-zinc-500",
      skills: [],
    }
  );
}

export function getRelevantSkills(domainKey, normalizedSkills = []) {
  const config = getDomainConfig(domainKey);
  const skillSet = new Set(normalizedSkills.map((s) => s.toLowerCase()));
  return config.skills.filter((s) => skillSet.has(s.toLowerCase())).slice(0, 5);
}
