// ── Weighted Skill Ontology ────────────────────────────────────────────────────
//
// PURPOSE
//   Refine recruiter ranking by giving discriminative value to specialised skills
//   without changing the global formula weights (0.55 domain / 0.30 skill / 0.15 activity).
//   Internally replaces:
//     matchedSkills.length / requestedSkills.length
//   with:
//     Σ weight(matchedSkill) / Σ weight(requestedSkill)
//
// WEIGHT SCALE
//   1.0  — generic / ubiquitous  (Git, Docker, Python, JavaScript, HTML)
//   1.5  — common but typed      (TypeScript, React, Node.js, REST)
//   2.0  — stack-defining        (Next.js, FastAPI, Express, Vue)
//   3.0  — specialised framework (Spring Boot, Redis, PostgreSQL, NestJS)
//   4.0  — high-value infra/tool (Kafka, LangChain, gRPC, Terraform, Kubeflow)
//   5.0  — research / runtime    (LoRA, RAG, eBPF, RAFT, CRDT, ZK-Proofs, TensorRT)
//
// PHILOSOPHY
//   • Weights reflect RECRUITER DISCRIMINATIVE VALUE, not popularity.
//   • React must not outweigh Kafka. Docker must not outweigh Spring Boot.
//   • Generic glue skills (Git, Linux, Bash) stay at 1.0.
//   • Weights should be conservative — when in doubt, go lower.
//
// FUTURE EVOLUTION (do NOT implement prematurely)
//   1. Dynamic TF-IDF weights: weight = log(totalUsers / usersWithSkill)
//      → makes rare skills automatically more valuable as the corpus grows.
//   2. Stack-specific weight packs: a "Java backend" pack upweights Hibernate, JPA,
//      Spring Security differently from a "Python backend" pack.
//   3. Repo co-occurrence modifier: if skill A almost always appears with skill B,
//      their individual discriminative value decreases (they're a bundle, not a signal).
//   4. Recruiter click-through feedback: clicked candidates' skills get positive weight
//      reinforcement over time.
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_SKILL_WEIGHT = 1.0; // unknown skills treated same as generic

// ── Ontology grouped by domain (for human readability + future pack slicing) ──

const SKILL_WEIGHTS_BY_DOMAIN = {

  // ── Frontend ───────────────────────────────────────────────────────────────
  frontend: {
    "html":               1.0,
    "css":                1.0,
    "javascript":         1.0,
    "typescript":         1.5,
    "react":              1.5,
    "vue":                2.0,
    "vue.js":             2.0,
    "angular":            2.0,
    "svelte":             3.0,
    "solid.js":           3.5,
    "qwik":               3.5,
    "next.js":            2.0,
    "nuxt.js":            2.5,
    "remix":              3.0,
    "astro":              3.0,
    "tailwind css":       1.0,
    "tailwind":           1.0,
    "sass":               1.0,
    "scss":               1.0,
    "styled-components":  1.5,
    "css modules":        1.5,
    "framer motion":      2.5,
    "gsap":               3.0,
    "three.js":           4.0,
    "webgl":              4.5,
    "webassembly":        4.5,
    "wasm":               4.5,
    "webrtc":             4.0,
    "web workers":        3.5,
    "redux":              2.0,
    "zustand":            2.5,
    "recoil":             2.5,
    "jotai":              2.5,
    "react query":        2.5,
    "tanstack query":     2.5,
    "apollo client":      2.5,
    "graphql":            2.5,
    "webpack":            1.5,
    "vite":               1.5,
    "esbuild":            2.0,
    "turbopack":          2.5,
    "storybook":          2.0,
    "jest":               1.5,
    "vitest":             2.0,
    "cypress":            2.0,
    "playwright":         2.5,
    "pwa":                2.5,
    "web components":     3.0,
    "accessibility":      2.0,
    "a11y":               2.0,
    "i18n":               2.0,
    "micro-frontends":    4.0,
  },

  // ── Backend ────────────────────────────────────────────────────────────────
  backend: {
    "node.js":            1.5,
    "nodejs":             1.5,
    "express":            1.5,
    "fastapi":            2.0,
    "django":             2.0,
    "flask":              1.5,
    "nestjs":             3.0,
    "hono":               3.0,
    "spring":             2.5,
    "spring boot":        4.0,
    "spring security":    3.5,
    "spring cloud":       4.0,
    "hibernate":          3.0,
    "jpa":                2.5,
    "asp.net core":       3.0,
    "rails":              2.5,
    "laravel":            2.5,
    "actix-web":          4.0,
    "axum":               4.0,
    "gin":                3.0,
    "fiber":              3.0,
    "graphql":            3.0,
    "grpc":               4.0,
    "protobuf":           3.5,
    "rest":               1.0,
    "rest api":           1.0,
    "websocket":          2.5,
    "oauth2":             2.5,
    "jwt":                1.5,
    "openapi":            2.0,
    "swagger":            1.5,
    "celery":             2.5,
    "rabbitmq":           3.0,
    "redis":              3.0,
    "caching":            2.0,
    "microservices":      3.0,
    "api gateway":        3.0,
    "rate limiting":      2.5,
    "event-driven":       3.5,
  },

  // ── DevOps ─────────────────────────────────────────────────────────────────
  devops: {
    "git":                1.0,
    "docker":             1.0,
    "linux":              1.0,
    "bash":               1.0,
    "kubernetes":         5.0,
    "helm":               3.5,
    "kustomize":          3.5,
    "terraform":          4.0,
    "pulumi":             4.0,
    "ansible":            3.5,
    "chef":               3.0,
    "puppet":             3.0,
    "ci/cd":              1.5,
    "github actions":     2.0,
    "jenkins":            2.0,
    "gitlab ci":          2.0,
    "circleci":           2.0,
    "argocd":             4.0,
    "fluxcd":             4.0,
    "gitops":             3.5,
    "prometheus":         3.0,
    "grafana":            2.5,
    "loki":               3.0,
    "opentelemetry":      3.5,
    "jaeger":             3.0,
    "elk stack":          3.0,
    "elasticsearch":      3.0,
    "istio":              4.5,
    "envoy":              4.0,
    "service mesh":       4.0,
    "vault":              3.5,
    "nginx":              2.0,
    "traefik":            2.5,
    "aws":                1.5,
    "gcp":                1.5,
    "azure":              1.5,
    "serverless":         2.5,
    "lambda":             2.5,
    "ebpf":               5.0,
    "cni":                4.5,
    "containerd":         3.0,
    "chaos engineering":  4.5,
    "sre":                3.5,
    "platform engineering": 4.0,
  },

  // ── Database ───────────────────────────────────────────────────────────────
  database: {
    "sql":                1.0,
    "postgresql":         3.0,
    "mysql":              2.0,
    "sqlite":             1.5,
    "mongodb":            2.0,
    "redis":              3.0,
    "elasticsearch":      3.5,
    "opensearch":         3.5,
    "cassandra":          4.0,
    "dynamodb":           3.0,
    "firestore":          2.0,
    "neo4j":              4.5,
    "arangodb":           4.0,
    "cockroachdb":        4.5,
    "tidb":               4.5,
    "clickhouse":         4.0,
    "timescaledb":        4.0,
    "influxdb":           3.5,
    "pinecone":           4.5,
    "weaviate":           4.5,
    "qdrant":             4.5,
    "chroma":             3.5,
    "milvus":             4.5,
    "vector database":    4.0,
    "database sharding":  4.5,
    "replication":        3.0,
    "indexing":           2.5,
    "query optimization": 3.5,
    "acid":               3.0,
    "database design":    2.5,
  },

  // ── Systems ────────────────────────────────────────────────────────────────
  systems: {
    "c":                  2.0,
    "c++":                2.0,
    "rust":               4.5,
    "go":                 3.0,
    "zig":                4.5,
    "assembly":           4.5,
    "linux kernel":       5.0,
    "memory management":  4.0,
    "concurrency":        3.5,
    "multithreading":     3.0,
    "lock-free":          5.0,
    "ipc":                3.5,
    "ebpf":               5.0,
    "fpga":               5.0,
    "llvm":               5.0,
    "compiler design":    5.0,
    "operating systems":  3.5,
    "systems programming":4.0,
    "risc-v":             5.0,
    "x86":                4.0,
    "arm":                3.5,
    "kernel modules":     5.0,
    "device drivers":     5.0,
    "virtualization":     4.0,
    "hypervisor":         4.5,
    "unikernels":         5.0,
  },

  // ── AI / ML ────────────────────────────────────────────────────────────────
  ai_ml: {
    "python":             1.0,
    "numpy":              1.5,
    "pandas":             1.5,
    "scikit-learn":       2.0,
    "tensorflow":         2.5,
    "pytorch":            3.0,
    "keras":              2.0,
    "jax":                4.0,
    "xgboost":            2.5,
    "lightgbm":           2.5,
    "catboost":           3.0,
    "mlflow":             3.0,
    "feature engineering":3.0,
    "deep learning":      3.5,
    "computer vision":    3.5,
    "object detection":   4.0,
    "image segmentation": 4.0,
    "yolov8":             3.5,
    "yolov5":             3.0,
    "resnet":             3.0,
    "vit":                4.0,
    "clip":               4.0,
    "facenet":            3.5,
    "mediapipe":          3.0,
    "albumentations":     2.5,
    "torchvision":        2.5,
    "detectron2":         4.0,
    "dlib":               2.5,
    "nlp":                3.5,
    "transformers":       4.0,
    "bert":               3.5,
    "spacy":              2.5,
    "nltk":               2.0,
    "stable diffusion":   4.0,
    "weights & biases":   3.0,
    "wandb":              3.0,
    "attention mechanism":4.5,
    "cuda":               4.5,
    "tensorrt":           5.0,
    "onnx":               4.0,
    "triton":             4.5,
    "vllm":               5.0,
    "distributed training":4.5,
    "model compression":  4.5,
    "quantization":       4.5,
    "knowledge distillation": 4.5,
    "neural architecture search": 5.0,
    "reinforcement learning": 4.5,
    "diffusion models":   4.5,
    "gans":               4.0,
    "graph neural networks": 4.5,
  },

  // ── GenAI ──────────────────────────────────────────────────────────────────
  genai: {
    "langchain":          4.0,
    "llamaindex":         4.0,
    "llama index":        4.0,
    "openai":             2.0,
    "openai api":         2.0,
    "huggingface":        3.0,
    "hugging face":       3.0,
    "rag":                5.0,
    "retrieval augmented generation": 5.0,
    "prompt engineering": 2.5,
    "fine-tuning":        4.5,
    "lora":               5.0,
    "qlora":              5.0,
    "peft":               4.5,
    "dpo":                5.0,
    "rlhf":               5.0,
    "vector embeddings":  3.5,
    "semantic search":    3.5,
    "llm evaluation":     4.0,
    "hallucination mitigation": 4.5,
    "chain-of-thought":   3.5,
    "function calling":   3.5,
    "tool use":           3.5,
    "multimodal":         4.0,
    "vision language models": 4.5,
    "llm inference":      4.0,
    "streaming inference":4.0,
    "context window":     3.0,
    "embedding models":   3.5,
    "reranking":          4.0,
    "guardrails":         4.0,
  },

  // ── Agentic AI ─────────────────────────────────────────────────────────────
  agentic_ai: {
    "langgraph":            5.0,
    "autogen":              4.5,
    "crewai":               4.5,
    "openai agents sdk":    4.0,
    "smolagents":           4.5,
    "agent frameworks":     4.0,
    "multi-agent systems":  5.0,
    "tool use":             3.5,
    "function calling":     3.5,
    "planning agents":      4.5,
    "memory systems":       4.0,
    "reflection":           4.0,
    "self-correction":      4.5,
    "agent orchestration":  5.0,
    "mcp":                      5.0,
    "model context protocol":   5.0,
    "a2a":                      4.5,
    "agentic workflows":        4.5,
    "human-in-the-loop":        3.5,
    "agent evaluation":         4.0,
    // Extended agentic ecosystem
    "google adk":               5.0,
    "adk":                      5.0,
    "tambo":                    4.5,
    "parlant":                  4.5,
    "pipecat":                  4.5,
    "livekit agents":           4.0,
    "deepgram":                 3.5,
    "firecrawl":                4.0,
    "e2b":                      4.5,
    "voice agent":              4.0,
    "rag":                      4.0,
    "multi-agent":              4.5,
    "multi-agent systems":      5.0,
    "tool calling":             3.5,
    "semantic search":          3.5,
    "vector search":            4.0,
    "context engineering":      4.5,
    "knowledge graphs":         4.0,
    "chromadb":                 3.5,
    "faiss":                    3.5,
    // Runtime / orchestration architecture
    "agent runtime":            4.5,
    "workflow runtime":         4.5,
    "execution graph":          4.5,
    "multi-model orchestration":5.0,
    "tool orchestration":       4.0,
    "self-learning agent":      4.5,
    "autonomous learning":      4.0,
    "planner executor":         4.5,
    "model routing":            4.5,
    "coordination framework":   4.5,
    "agent infrastructure":     4.5,
    "agent factory":            4.5,
    "distributed multi-agent":  5.0,
  },

  // ── MLOps ──────────────────────────────────────────────────────────────────
  mlops: {
    "mlflow":             3.0,
    "kubeflow":           4.5,
    "airflow":            3.5,
    "prefect":            3.5,
    "dagster":            4.0,
    "dbt":                3.5,
    "dvc":                3.5,
    "feast":              4.0,
    "bentoml":            4.0,
    "seldon":             4.5,
    "ray serve":          4.5,
    "triton inference server": 5.0,
    "model monitoring":   3.5,
    "data drift":         3.5,
    "feature store":      4.0,
    "model registry":     3.5,
    "experiment tracking":3.0,
    "pipeline orchestration": 4.0,
    "a/b testing":        3.0,
    "shadow deployment":  4.0,
    "canary deployment":  3.5,
    "model versioning":   3.0,
    "continuous training":4.0,
  },

  // ── Data Science ───────────────────────────────────────────────────────────
  data_science: {
    "statistics":         2.5,
    "probability":        2.5,
    "linear algebra":     2.5,
    "calculus":           2.0,
    "hypothesis testing": 3.0,
    "time series":        3.5,
    "forecasting":        3.5,
    "bayesian inference": 4.5,
    "causal inference":   5.0,
    "survival analysis":  4.5,
    "a/b testing":        3.0,
    "data visualization": 2.0,
    "matplotlib":         1.5,
    "seaborn":            1.5,
    "plotly":             2.0,
    "tableau":            2.0,
    "power bi":           2.0,
    "apache spark":       4.0,
    "hadoop":             3.0,
    "dask":               3.5,
    "polars":             3.5,
    "sql":                1.0,
    "sql analytics":      2.5,
    "data pipelines":     3.0,
    "etl":                2.5,
    "data modeling":      3.0,
    "dimensionality reduction": 3.5,
    "anomaly detection":  3.5,
  },

  // ── Data Engineering ──────────────────────────────────────────────────────
  data_engineering: {
    "spark":                3.5,
    "pyspark":              4.0,
    "apache spark":         4.0,
    "airflow":              3.5,
    "apache airflow":       3.5,
    "dbt":                  4.0,
    "data build tool":      4.0,
    "flink":                4.5,
    "apache flink":         4.5,
    "hadoop":               3.0,
    "hive":                 3.0,
    "hdfs":                 3.0,
    "snowflake":            3.5,
    "databricks":           4.0,
    "bigquery":             3.5,
    "redshift":             3.0,
    "data warehouse":       3.0,
    "data lake":            3.0,
    "delta lake":           4.0,
    "apache iceberg":       4.0,
    "lakehouse":            3.5,
    "parquet":              2.5,
    "avro":                 2.5,
    "etl":                  2.5,
    "data pipeline":        2.5,
    "data ingestion":       2.5,
    "batch processing":     3.0,
    "stream processing":    3.5,
    "data orchestration":   3.5,
    "dimensional modeling": 4.0,
    "data quality":         3.0,
    "data lineage":         3.5,
    "data catalog":         3.0,
    "data mesh":            4.0,
    "kinesis":              3.0,
    "aws glue":             3.0,
    "cloud data platform":  3.5,
    "analytics engineering":4.0,
    "sql analytics":        2.5,
    "prefect":              3.5,
    "dagster":              4.0,
  },

  // ── Algorithms ─────────────────────────────────────────────────────────────
  algorithms: {
    "data structures":    2.5,
    "dynamic programming":4.0,
    "graph algorithms":   4.0,
    "greedy":             3.0,
    "backtracking":       3.0,
    "binary search":      2.5,
    "sorting":            2.0,
    "two pointers":       2.5,
    "sliding window":     2.5,
    "segment trees":      4.5,
    "fenwick tree":       4.5,
    "suffix arrays":      5.0,
    "suffix automaton":   5.0,
    "flow networks":      4.5,
    "max flow":           4.5,
    "bipartite matching": 4.5,
    "string algorithms":  4.0,
    "kmp":                4.0,
    "aho-corasick":       5.0,
    "computational geometry": 5.0,
    "number theory":      4.5,
    "modular arithmetic": 3.5,
    "matrix exponentiation": 4.5,
    "game theory":        4.5,
    "competitive programming": 3.5,
    "randomized algorithms": 4.0,
    "approximation algorithms": 4.5,
  },

  // ── Cybersecurity ──────────────────────────────────────────────────────────
  cybersecurity: {
    "penetration testing":4.0,
    "pentesting":         4.0,
    "ctf":                3.5,
    "reverse engineering":5.0,
    "exploit development":5.0,
    "web security":       3.0,
    "owasp":              2.5,
    "network security":   3.0,
    "cryptography":       4.5,
    "malware analysis":   5.0,
    "forensics":          4.0,
    "threat modeling":    4.0,
    "siem":               3.5,
    "zero trust":         3.5,
    "devsecops":          3.0,
    "vulnerability assessment": 3.5,
    "metasploit":         4.0,
    "burp suite":         3.5,
    "wireshark":          3.0,
    "osint":              3.5,
    "social engineering": 4.0,
    "red team":           5.0,
    "blue team":          4.0,
    "incident response":  4.0,
    "threat intelligence":4.5,
    "secure coding":      3.0,
    "pki":                3.5,
  },

  // ── Blockchain ─────────────────────────────────────────────────────────────
  blockchain: {
    "solidity":           4.0,
    "smart contracts":    4.0,
    "ethereum":           3.5,
    "web3.js":            3.0,
    "ethers.js":          3.0,
    "hardhat":            3.5,
    "foundry":            4.0,
    "defi":               4.0,
    "nft":                2.5,
    "ipfs":               3.0,
    "zero-knowledge proofs": 5.0,
    "zk-snarks":          5.0,
    "zk-starks":          5.0,
    "layer 2":            4.5,
    "optimistic rollups": 4.5,
    "zk rollups":         5.0,
    "consensus mechanisms": 4.5,
    "proof of stake":     4.0,
    "merkle trees":       4.0,
    "tokenomics":         3.0,
    "dao":                3.5,
    "cross-chain":        4.5,
    "bridges":            4.0,
    "evm":                4.0,
    "cairo":              5.0,
    "rust (blockchain)":  4.5,
  },

  // ── Embedded ───────────────────────────────────────────────────────────────
  embedded: {
    "c":                  2.0,
    "c++":                2.0,
    "assembly":           4.5,
    "arduino":            2.0,
    "raspberry pi":       2.0,
    "rtos":               4.5,
    "freertos":           4.5,
    "zephyr":             4.5,
    "bare metal":         4.5,
    "uart":               3.5,
    "spi":                3.5,
    "i2c":                3.5,
    "can bus":            4.0,
    "fpga":               5.0,
    "verilog":            5.0,
    "vhdl":               5.0,
    "hdl":                5.0,
    "embedded linux":     4.0,
    "yocto":              4.5,
    "buildroot":          4.0,
    "bootloader":         4.5,
    "u-boot":             4.5,
    "device drivers":     4.5,
    "dma":                4.5,
    "interrupt handling": 4.0,
    "autosar":            5.0,
    "misra c":            4.5,
    "risc-v":             5.0,
    "arm cortex":         4.0,
    "power management":   4.0,
    "iot":                2.5,
  },

  // ── Networking ─────────────────────────────────────────────────────────────
  networking: {
    "tcp/ip":             2.5,
    "dns":                2.0,
    "http":               1.5,
    "https":              1.5,
    "http/2":             2.5,
    "http/3":             3.0,
    "quic":               4.0,
    "bgp":                4.5,
    "ospf":               4.0,
    "mpls":               4.5,
    "sdn":                5.0,
    "nfv":                5.0,
    "openflow":           5.0,
    "p4":                 5.0,
    "dpdk":               5.0,
    "load balancing":     2.5,
    "cdn":                2.5,
    "firewall":           2.5,
    "vpn":                2.5,
    "ipsec":              3.5,
    "network simulation": 4.0,
    "wireshark":          3.0,
    "packet analysis":    3.5,
    "5g":                 5.0,
    "network slicing":    5.0,
    "overlay networks":   4.0,
    "vxlan":              4.0,
    "network automation": 4.0,
  },

  // ── Distributed Systems ────────────────────────────────────────────────────
  distributed_systems: {
    "kafka":              4.0,
    "apache kafka":       4.0,
    "rabbitmq":           3.0,
    "nats":               3.5,
    "apache pulsar":      4.5,
    "zookeeper":          3.5,
    "etcd":               4.0,
    "raft":               5.0,
    "raft consensus":     5.0,
    "paxos":              5.0,
    "crdt":               5.0,
    "consistent hashing": 4.5,
    "distributed transactions": 4.5,
    "two-phase commit":   4.5,
    "saga pattern":       4.0,
    "event sourcing":     4.0,
    "cqrs":               4.0,
    "apache flink":       4.5,
    "apache spark":       4.0,
    "grpc":               4.0,
    "protobuf":           3.5,
    "cap theorem":        4.0,
    "eventual consistency": 4.0,
    "vector clocks":      5.0,
    "distributed locks":  4.5,
    "leader election":    4.5,
    "gossip protocol":    5.0,
    "chord":              5.0,
    "dynamo":             5.0,
    "spanner":            5.0,
  },
};

// ── Aliases / synonyms ─────────────────────────────────────────────────────────
// Maps alternate tokens → canonical token present in the ontology above.
// Normalise user input before lookup so "Next.js", "nextjs", "next js" all resolve.

const SKILL_ALIASES = {
  // REST API — all recruiter query variants → canonical stored token
  "rest_api":            "rest api",
  "rest-api":            "rest api",
  "restapi":             "rest api",
  "restful api":         "rest api",
  "restful-api":         "rest api",
  "restful_api":         "rest api",
  "restful":             "rest api",
  "json api":            "rest api",
  "http api":            "rest api",
  "api development":     "rest api",
  "backend api":         "rest api",
  "web api":             "rest api",
  "nextjs":              "next.js",
  "next js":             "next.js",
  "vuejs":               "vue.js",
  "vue js":              "vue.js",
  "reactjs":             "react",
  "react.js":            "react",
  "nodejs":              "node.js",
  "node js":             "node.js",
  "expressjs":           "express",
  "express.js":          "express",
  "nestjs":              "nestjs",
  "nest.js":             "nestjs",
  "threejs":             "three.js",
  "three js":            "three.js",
  "postgres":            "postgresql",
  "pg":                  "postgresql",
  "mongo":               "mongodb",
  "k8s":                 "kubernetes",
  "tf":                  "terraform",
  "gh actions":          "github actions",
  "langchain":           "langchain",
  "lang chain":          "langchain",
  "llama index":         "llamaindex",
  "llama-index":         "llamaindex",
  "hugging face":        "huggingface",
  "hf":                  "huggingface",
  "gpt":                 "openai api",
  "openai gpt":          "openai api",
  "retrieval augmented": "rag",
  "retrieval-augmented generation": "rag",
  "low-rank adaptation": "lora",
  "peft lora":           "lora",
  "zkp":                 "zero-knowledge proofs",
  "zk proofs":           "zero-knowledge proofs",
  "zk-proof":            "zero-knowledge proofs",
  "zksnark":             "zk-snarks",
  "zk snark":            "zk-snarks",
  "zkstark":             "zk-starks",
  "tailwindcss":         "tailwind css",
  "tailwind-css":        "tailwind css",
  "scss":                "sass",
  "freertos":            "freertos",
  "free rtos":           "freertos",
  "apache spark":        "apache spark",
  "pyspark":             "pyspark",
  "apache flink":        "apache flink",
  "dbt-core":            "dbt",
  "airflow":             "airflow",
  "apache-airflow":      "airflow",
  "kafka":               "kafka",
  "spring-boot":         "spring boot",
  "springboot":          "spring boot",
  "asp.net":             "asp.net core",
  "dotnet":              "asp.net core",
  ".net core":           "asp.net core",
  "rag pipeline":        "rag",
  "retrieval augmented": "rag",
  "google adk":          "adk",
  "google-adk":          "adk",
  "agent development kit": "adk",
  "pipecat-ai":          "pipecat",
  "livekit-agents":      "livekit agents",
  "deepgram-sdk":        "deepgram",
  "chromadb":            "chromadb",
  "chroma":              "chromadb",
  "faiss-cpu":           "faiss",
  "firecrawl-py":        "firecrawl",
  "e2b-code-interpreter": "e2b",
  "multi-agent":         "multi-agent systems",
  "multi-agent-systems": "multi-agent systems",
  "tool-calling":        "tool calling",
  "function-calling":    "tool calling",
  "vector-search":       "vector search",
  "semantic-search":     "semantic search",
  "context-engineering": "context engineering",
  "knowledge-graph":     "knowledge graphs",
  "graph-rag":           "knowledge graphs",
  "graphrag":            "knowledge graphs",
  "speech-to-text":      "speech-to-text",
  "stt":                 "speech-to-text",
  "a2a protocol":        "a2a",
  "vllm":                "vllm",
  "triton server":       "triton inference server",
  "triton":              "triton",
  "ray":                 "ray serve",
  "ebpf":                "ebpf",
  "bpf":                 "ebpf",
};

// ── Build flat lookup map ──────────────────────────────────────────────────────
// Merge all domain sections into one flat map for O(1) lookup.

const SKILL_WEIGHTS = (() => {
  const flat = {};
  for (const domain of Object.values(SKILL_WEIGHTS_BY_DOMAIN)) {
    for (const [skill, weight] of Object.entries(domain)) {
      // Later domains do not overwrite earlier ones for shared skills (e.g. grpc appears in backend + distributed_systems)
      if (!(skill in flat)) flat[skill] = weight;
    }
  }
  return flat;
})();

// ── Public API ─────────────────────────────────────────────────────────────────

/**
 * Return the recruiter-discriminative weight for a skill token.
 *
 * Lookup order:
 *   1. Resolve alias → canonical token
 *   2. Direct flat map hit
 *   3. DEFAULT_SKILL_WEIGHT for unknown skills
 *
 * Always call with a lowercased, trimmed token.
 *
 * @param  {string} skill  — lowercased, trimmed skill token
 * @returns {number}       — weight in [1.0, 5.0]
 */
function getSkillWeight(skill) {
  const canonical = SKILL_ALIASES[skill] || skill;
  return SKILL_WEIGHTS[canonical] ?? DEFAULT_SKILL_WEIGHT;
}

/**
 * Build a { skill → weight } map for a list of requested skill tokens.
 * Use this to feed into weighted skill scoring in searchService.
 *
 * @param  {string[]} skills — lowercased, trimmed skill tokens
 * @returns {{ [skill: string]: number }}
 */
function buildSkillWeightMap(skills) {
  const map = {};
  for (const skill of skills) map[skill] = getSkillWeight(skill);
  return map;
}

module.exports = {
  SKILL_WEIGHTS,
  SKILL_WEIGHTS_BY_DOMAIN,
  SKILL_ALIASES,
  DEFAULT_SKILL_WEIGHT,
  getSkillWeight,
  buildSkillWeightMap,
};
