# Auto-derived from backend/services/skills/skillOntology.js and services/semantic/ontology.js
# Regenerate this file whenever those JS files change.
# Used as a fallback when the Node backend is unreachable at startup.

BUNDLED_TEXT_KEYWORDS = [
    ["javascript", "JavaScript"],
    ["typescript", "TypeScript"],
    ["python", "Python"],
    ["golang", "Go"],
    ["java", "Java"],
    ["kotlin", "Kotlin"],
    ["swift", "Swift"],
    ["dart", "Dart"],
    ["rust", "Rust"],
    ["ruby", "Ruby"],
    ["php", "PHP"],
    ["scala", "Scala"],
    ["elixir", "Elixir"],
    ["haskell", "Haskell"],
    ["flutter", "Flutter"],
    ["react", "React"],
    ["reactjs", "React"],
    ["react.js", "React"],
    ["angular", "Angular"],
    ["svelte", "Svelte"],
    ["sveltekit", "SvelteKit"],
    ["django", "Django"],
    ["flask", "Flask"],
    ["fastapi", "FastAPI"],
    ["nextjs", "Next.js"],
    ["next.js", "Next.js"],
    ["vuejs", "Vue"],
    ["vue.js", "Vue"],
    ["spring boot", "Spring Boot"],
    ["react native", "React Native"],
    ["node.js", "Node.js"],
    ["nodejs", "Node.js"],
    ["pytorch", "PyTorch"],
    ["tensorflow", "TensorFlow"],
    ["scikit-learn", "scikit-learn"],
    ["sklearn", "scikit-learn"],
    # CV models
    ["yolov8", "YOLOv8"],
    ["yolov5", "YOLOv8"],
    ["yolo", "YOLOv8"],
    ["ultralytics", "YOLOv8"],
    ["resnet", "ResNet"],
    ["vit", "ViT"],
    ["vision transformer", "ViT"],
    ["clip", "CLIP"],
    ["facenet", "FaceNet"],
    ["mediapipe", "MediaPipe"],
    ["media pipe", "MediaPipe"],
    ["albumentations", "Albumentations"],
    ["torchvision", "TorchVision"],
    ["detectron2", "Detectron2"],
    ["dlib", "dlib"],
    # NLP
    ["bert", "BERT"],
    ["roberta", "BERT"],
    ["distilbert", "BERT"],
    ["spacy", "spaCy"],
    ["nltk", "NLTK"],
    # GenAI / Diffusion
    ["stable diffusion", "Stable Diffusion"],
    ["stable-diffusion", "Stable Diffusion"],
    ["sdxl", "Stable Diffusion"],
    # Experiment tracking
    ["wandb", "Weights & Biases"],
    ["weights & biases", "Weights & Biases"],
    ["weights and biases", "Weights & Biases"],
    ["langchain", "LangChain"],
    ["langgraph", "LangGraph"],
    ["crewai", "CrewAI"],
    ["crew ai", "CrewAI"],
    ["autogen", "AutoGen"],
    ["pyautogen", "AutoGen"],
    ["autogen-agentchat", "AutoGen"],
    ["pydantic ai", "Pydantic AI"],
    ["pydantic-ai", "Pydantic AI"],
    ["pydanticai", "Pydantic AI"],
    ["agno", "Agno"],
    ["smolagents", "smolagents"],
    ["smol agents", "smolagents"],
    ["openai", "OpenAI SDK"],
    ["openai sdk", "OpenAI SDK"],
    ["anthropic", "Anthropic SDK"],
    ["anthropic sdk", "Anthropic SDK"],
    ["adk", "ADK"],
    ["google adk", "ADK"],
    ["agent development kit", "ADK"],
    ["tailwindcss", "Tailwind CSS"],
    ["tailwind css", "Tailwind CSS"],
    ["graphql", "GraphQL"],
    ["hugging face", "Hugging Face"],
    ["huggingface", "Hugging Face"],
    ["mongodb", "MongoDB"],
    ["postgresql", "PostgreSQL"],
    ["postgres", "PostgreSQL"],
    ["mysql", "MySQL"],
    ["sqlite", "SQLite"],
    ["redis", "Redis"],
    ["firebase", "Firebase"],
    ["supabase", "Supabase"],
    ["docker", "Docker"],
    ["kubernetes", "Kubernetes"],
    ["terraform", "Terraform"],
    ["linux", "Linux"],
    ["ubuntu", "Linux"],
    ["figma", "Figma"],
    ["postman", "Postman"],
    ["vscode", "VSCode"],
    ["visual studio code", "VSCode"],
    ["android studio", "Android Studio"],
    ["github actions", "GitHub Actions"],
    ["ollama", "Ollama"],
    ["vllm", "vLLM"],
    ["peft", "PEFT"],
    ["lora", "PEFT"],
    ["qlora", "PEFT"],
    ["sentence-transformers", "SentenceTransformers"],
    ["sentence transformers", "SentenceTransformers"],
    ["haystack", "Haystack"],
    ["dspy", "DSPy"],
    ["semantic kernel", "Semantic Kernel"],
    ["pyspark", "PySpark"],
    ["apache spark", "PySpark"],
    ["databricks", "Databricks"],
    ["snowflake", "Snowflake"],
    ["clickhouse", "ClickHouse"],
    ["airbyte", "Airbyte"],
    ["apache flink", "Flink"],
    ["rest api", "REST API"],
    ["restful api", "REST API"],
    ["rest-api", "REST API"],
    ["restapi", "REST API"],
    ["restful-api", "REST API"],
    ["restful_api", "REST API"],
    ["rest_api", "REST API"],
    ["restful", "REST API"],
    ["json api", "REST API"],
    ["http api", "REST API"],
    ["api development", "REST API"],
    ["backend api", "REST API"],
    ["kafka", "Kafka"],
    ["rabbitmq", "RabbitMQ"],
    ["grpc", "gRPC"],
    ["traefik", "Traefik"],
    ["consul", "Consul"],
    ["zookeeper", "ZooKeeper"],
    ["burp suite", "Burp Suite"],
    ["metasploit", "Metasploit"],
    ["wireshark", "Wireshark"],
    ["nmap", "Nmap"],
    ["kali linux", "Kali Linux"],
    ["vercel", "Vercel"],
    ["netlify", "Netlify"],
    ["heroku", "Heroku"],
    ["cloudflare", "Cloudflare"],
    ["digitalocean", "DigitalOcean"],
    ["aws", "AWS"],
    ["azure", "Azure"],
    ["google cloud", "GCP"],
    ["gcp", "GCP"],
]

BUNDLED_SKILL_ONTOLOGY = {
    "languages": [
        {"display": "JavaScript", "aliases": ["javascript", "js"]},
        {"display": "TypeScript", "aliases": ["typescript", "ts"]},
        {"display": "Python", "aliases": ["python", "py"]},
        {"display": "Java", "aliases": ["java"]},
        {"display": "C++", "aliases": ["c++", "cpp", "cplusplus", "c-plus-plus"]},
        {"display": "C#", "aliases": ["c#", "csharp", "c-sharp"]},
        {"display": "Go", "aliases": ["golang"]},
        {"display": "Rust", "aliases": ["rust"]},
        {"display": "Kotlin", "aliases": ["kotlin"]},
        {"display": "Swift", "aliases": ["swift"]},
        {"display": "Dart", "aliases": ["dart"]},
        {"display": "Ruby", "aliases": ["ruby"]},
        {"display": "PHP", "aliases": ["php"]},
        {"display": "Scala", "aliases": ["scala"]},
        {"display": "Elixir", "aliases": ["elixir"]},
        {"display": "Haskell", "aliases": ["haskell"]},
        {"display": "Shell", "aliases": ["shell", "bash", "zsh"]},
        {"display": "R", "aliases": ["r-language"]},
        {"display": "C", "aliases": ["c-language"]},
    ],
    "frameworks": [
        {"display": "React", "aliases": ["react", "reactjs", "react.js", "react-js"]},
        {"display": "Next.js", "aliases": ["next", "nextjs", "next.js", "next-js"]},
        {"display": "Vue", "aliases": ["vue", "vuejs", "vue.js", "vue-js"]},
        {"display": "Nuxt", "aliases": ["nuxt", "nuxtjs", "nuxt.js"]},
        {"display": "Angular", "aliases": ["angular", "angularjs"]},
        {"display": "Svelte", "aliases": ["svelte"]},
        {"display": "SvelteKit", "aliases": ["sveltekit"]},
        {"display": "Astro", "aliases": ["astro"]},
        {"display": "Remix", "aliases": ["remix"]},
        {"display": "Express", "aliases": ["express", "expressjs", "express.js"]},
        {"display": "Fastify", "aliases": ["fastify"]},
        {"display": "NestJS", "aliases": ["nestjs", "nest"]},
        {"display": "Koa", "aliases": ["koa"]},
        {"display": "Hono", "aliases": ["hono"]},
        {"display": "FastAPI", "aliases": ["fastapi", "fast-api", "fast api"]},
        {"display": "Flask", "aliases": ["flask"]},
        {"display": "Django", "aliases": ["django"]},
        {"display": "Starlette", "aliases": ["starlette"]},
        {"display": "aiohttp", "aliases": ["aiohttp"]},
        {"display": "Rails", "aliases": ["rails", "ruby-on-rails", "ruby on rails", "ror"]},
        {"display": "Laravel", "aliases": ["laravel"]},
        {"display": "Spring Boot", "aliases": ["spring-boot", "springboot", "spring boot"]},
        {"display": "Spring Security", "aliases": ["spring-security", "spring security"]},
        {"display": "Gin", "aliases": ["gin"]},
        {"display": "Fiber", "aliases": ["fiber"]},
        {"display": "Axum", "aliases": ["axum"]},
        {"display": "Rocket", "aliases": ["rocket"]},
        {"display": "Actix-web", "aliases": ["actix-web", "actix web"]},
        {"display": "Flutter", "aliases": ["flutter"]},
        {"display": "React Native", "aliases": ["react-native", "react native", "reactnative"]},
        {"display": "Expo", "aliases": ["expo"]},
        {"display": "Node.js", "aliases": ["nodejs", "node.js", "node-js"]},
    ],
    "libraries": [
        {"display": "PyTorch", "aliases": ["pytorch", "torch"]},
        {"display": "TensorFlow", "aliases": ["tensorflow", "tf"]},
        {"display": "Keras", "aliases": ["keras"]},
        {"display": "XGBoost", "aliases": ["xgboost"]},
        {"display": "LightGBM", "aliases": ["lightgbm"]},
        {"display": "OpenCV", "aliases": ["opencv", "cv2"]},
        {"display": "YOLOv8", "aliases": ["yolov8", "yolov5", "yolo", "ultralytics"]},
        {"display": "ResNet", "aliases": ["resnet", "resnet50", "resnet101", "resnet152"]},
        {"display": "ViT", "aliases": ["vit", "vision transformer", "vision-transformer"]},
        {"display": "CLIP", "aliases": ["clip", "openai clip"]},
        {"display": "FaceNet", "aliases": ["facenet"]},
        {"display": "MediaPipe", "aliases": ["mediapipe", "media pipe"]},
        {"display": "Albumentations", "aliases": ["albumentations"]},
        {"display": "TorchVision", "aliases": ["torchvision", "torch vision"]},
        {"display": "Detectron2", "aliases": ["detectron2", "detectron"]},
        {"display": "dlib", "aliases": ["dlib"]},
        {"display": "BERT", "aliases": ["bert", "roberta", "distilbert", "albert"]},
        {"display": "spaCy", "aliases": ["spacy"]},
        {"display": "NLTK", "aliases": ["nltk", "natural language toolkit"]},
        {"display": "Stable Diffusion", "aliases": ["stable diffusion", "stablediffusion", "stable-diffusion", "sdxl", "sd-xl"]},
        {"display": "Weights & Biases", "aliases": ["weights & biases", "wandb", "w&b", "weights and biases"]},
        {"display": "Transformers", "aliases": ["transformers"]},
        {"display": "Diffusers", "aliases": ["diffusers"]},
        {"display": "JAX", "aliases": ["jax"]},
        {"display": "NumPy", "aliases": ["numpy", "np"]},
        {"display": "Pandas", "aliases": ["pandas", "pd"]},
        {"display": "Matplotlib", "aliases": ["matplotlib"]},
        {"display": "Seaborn", "aliases": ["seaborn"]},
        {"display": "Plotly", "aliases": ["plotly"]},
        {"display": "SciPy", "aliases": ["scipy"]},
        {"display": "scikit-learn", "aliases": ["scikit-learn", "sklearn", "scikit learn"]},
        {"display": "LangChain", "aliases": ["langchain", "lang-chain"]},
        {"display": "LangGraph", "aliases": ["langgraph"]},
        {"display": "LlamaIndex", "aliases": ["llama-index", "llama index", "llamaindex"]},
        {"display": "Hugging Face", "aliases": ["hugging-face", "hugging face", "huggingface", "huggingface-hub"]},
        {"display": "OpenAI SDK", "aliases": ["openai"]},
        {"display": "Anthropic SDK", "aliases": ["anthropic"]},
        {"display": "Gemini", "aliases": ["gemini", "gemini-api", "google-generativeai"]},
        {"display": "Groq", "aliases": ["groq"]},
        {"display": "Cohere", "aliases": ["cohere"]},
        {"display": "MistralAI", "aliases": ["mistralai"]},
        {"display": "CrewAI", "aliases": ["crewai"]},
        {"display": "AutoGen", "aliases": ["autogen", "pyautogen", "autogen-agentchat", "microsoft-autogen", "ag2"]},
        {"display": "smolagents", "aliases": ["smolagents"]},
        {"display": "Agno", "aliases": ["agno"]},
        {"display": "ADK", "aliases": ["adk", "google-adk", "google adk", "agent development kit", "google-generativeai-adk"]},
        {"display": "MCP", "aliases": ["mcp", "model-context-protocol", "model context protocol", "modelcontextprotocol"]},
        {"display": "Pydantic AI", "aliases": ["pydantic-ai", "pydantic ai", "pydanticai"]},
        {"display": "vLLM", "aliases": ["vllm"]},
        {"display": "PEFT", "aliases": ["peft", "lora", "qlora", "loralib"]},
        {"display": "SentenceTransformers", "aliases": ["sentence-transformers", "sentence transformers", "sentencetransformers"]},
        {"display": "Haystack", "aliases": ["haystack", "haystack-ai", "deepset-haystack"]},
        {"display": "DSPy", "aliases": ["dspy"]},
        {"display": "Semantic Kernel", "aliases": ["semantic-kernel", "semantic kernel"]},
        {"display": "MLflow", "aliases": ["mlflow"]},
        {"display": "Airflow", "aliases": ["airflow"]},
        {"display": "Prefect", "aliases": ["prefect"]},
        {"display": "Ray", "aliases": ["ray"]},
        {"display": "PySpark", "aliases": ["pyspark", "spark", "apache-spark", "apache spark"]},
        {"display": "dbt", "aliases": ["dbt", "dbt-core"]},
        {"display": "Flink", "aliases": ["flink", "apache-flink", "apache flink"]},
        {"display": "gRPC", "aliases": ["grpc", "grpcio"]},
        {"display": "Kafka", "aliases": ["kafka", "confluent-kafka", "kafka-python"]},
        {"display": "RabbitMQ", "aliases": ["rabbitmq", "pika", "amqp"]},
        {"display": "Tailwind CSS", "aliases": ["tailwindcss", "tailwind", "tailwind-css", "tailwind css"]},
        {"display": "Redux", "aliases": ["redux"]},
        {"display": "Zustand", "aliases": ["zustand"]},
        {"display": "Axios", "aliases": ["axios"]},
        {"display": "GraphQL", "aliases": ["graphql"]},
        {"display": "Socket.io", "aliases": ["socket-io", "socket.io", "socketio", "socket io"]},
        {"display": "Prisma", "aliases": ["prisma"]},
        {"display": "SQLAlchemy", "aliases": ["sqlalchemy"]},
        {"display": "Mongoose", "aliases": ["mongoose"]},
    ],
    "databases": [
        {"display": "MongoDB", "aliases": ["mongodb", "mongo", "pymongo"]},
        {"display": "PostgreSQL", "aliases": ["postgresql", "postgres", "pg", "psycopg2", "psycopg"]},
        {"display": "MySQL", "aliases": ["mysql", "mysql2"]},
        {"display": "SQLite", "aliases": ["sqlite", "sqlite3"]},
        {"display": "Redis", "aliases": ["redis", "ioredis"]},
        {"display": "Firebase", "aliases": ["firebase"]},
        {"display": "Supabase", "aliases": ["supabase"]},
        {"display": "Pinecone", "aliases": ["pinecone"]},
        {"display": "Weaviate", "aliases": ["weaviate"]},
        {"display": "Neo4j", "aliases": ["neo4j"]},
        {"display": "Cassandra", "aliases": ["cassandra"]},
        {"display": "Qdrant", "aliases": ["qdrant", "qdrant-client", "qdrant client"]},
        {"display": "ChromaDB", "aliases": ["chromadb", "chroma-db", "chroma db", "chromadb-client"]},
        {"display": "FAISS", "aliases": ["faiss", "faiss-cpu", "faiss-gpu"]},
        {"display": "DynamoDB", "aliases": ["dynamodb"]},
        {"display": "Elasticsearch", "aliases": ["elasticsearch", "elastic"]},
        {"display": "Snowflake", "aliases": ["snowflake"]},
        {"display": "Databricks", "aliases": ["databricks"]},
        {"display": "ClickHouse", "aliases": ["clickhouse"]},
    ],
    "tools": [
        {"display": "Git", "aliases": ["git"]},
        {"display": "GitHub", "aliases": ["github"]},
        {"display": "Docker", "aliases": ["docker"]},
        {"display": "Kubernetes", "aliases": ["kubernetes", "k8s"]},
        {"display": "Terraform", "aliases": ["terraform"]},
        {"display": "Ansible", "aliases": ["ansible"]},
        {"display": "Nginx", "aliases": ["nginx"]},
        {"display": "GitHub Actions", "aliases": ["github-actions", "github actions"]},
        {"display": "AWS", "aliases": ["aws", "amazon web services"]},
        {"display": "GCP", "aliases": ["gcp", "google cloud", "google-cloud"]},
        {"display": "Azure", "aliases": ["azure", "microsoft azure"]},
        {"display": "Vercel", "aliases": ["vercel"]},
        {"display": "Netlify", "aliases": ["netlify"]},
        {"display": "Heroku", "aliases": ["heroku"]},
        {"display": "Cloudflare", "aliases": ["cloudflare"]},
        {"display": "DigitalOcean", "aliases": ["digitalocean", "digital ocean"]},
        {"display": "Linux", "aliases": ["linux", "ubuntu", "debian", "centos", "arch linux"]},
        {"display": "REST API", "aliases": ["rest api", "rest_api", "rest-api", "restapi", "restful api", "restful-api", "restful_api", "rest", "restful", "api development", "backend api", "web api", "http api"]},
        {"display": "Jest", "aliases": ["jest"]},
        {"display": "Pytest", "aliases": ["pytest"]},
        {"display": "Playwright", "aliases": ["playwright"]},
        {"display": "Cypress", "aliases": ["cypress"]},
        {"display": "Vite", "aliases": ["vite"]},
        {"display": "Webpack", "aliases": ["webpack"]},
        {"display": "Prometheus", "aliases": ["prometheus"]},
        {"display": "Grafana", "aliases": ["grafana"]},
        {"display": "Burp Suite", "aliases": ["burpsuite", "burp suite", "burp-suite"]},
        {"display": "Metasploit", "aliases": ["metasploit", "msfconsole"]},
        {"display": "Wireshark", "aliases": ["wireshark"]},
        {"display": "Nmap", "aliases": ["nmap"]},
        {"display": "Kali Linux", "aliases": ["kali", "kali linux", "kali-linux"]},
        {"display": "Ollama", "aliases": ["ollama"]},
        {"display": "Figma", "aliases": ["figma"]},
        {"display": "Postman", "aliases": ["postman"]},
        {"display": "VSCode", "aliases": ["vscode", "visual studio code", "vs code"]},
    ],
}

BUNDLED_DOMAIN_RULES = {
    "ai_ml": [
        "neural", "classification", "detection", "vision", "nlp",
        "machine learning", "deep learning", "cnn", "rnn",
        "resnet", "yolo", "fine-tuning", "finetuning", "fine tune", "fine-tuned", "fine tuned",
        "training dataset", "ml dataset", "training data", "model training", "huggingface",
        "computer vision", "image segmentation", "object detection",
        "natural language processing", "speech recognition",
        "siamese network", "encoder decoder",
        "time series", "forecasting", "anomaly detection",
        "prediction", "ml prediction", "model prediction", "prediction api",
        "recommendation system", "recommendation engine", "collaborative filtering",
        "inference api", "ml inference api", "model serving api",
        "classification system", "classification model",
        "detection system", "disease detection",
        "ranking model", "personalization", "content ranking",
        "image recognition", "recognition model",
        "regression", "linear regression", "logistic regression",
        "feature engineering", "feature extraction", "feature selection",
        "analytics pipeline", "ml pipeline",
        "ai powered", "ai-powered", "ai assisted",
        # NLP / Transformer-specific
        "transformer", "bert", "roberta", "embedding", "embeddings", "sentence embedding",
        "semantic embedding", "text classification", "sentiment analysis",
        "named entity recognition", "ner", "question answering",
        "summarization", "text summarization", "abstractive summarization",
        "token classification", "sequence labeling", "semantic similarity",
        "language model", "language modeling", "multilingual model",
        "intent classification", "intent detection", "entity extraction",
        # General ML signals
        "accuracy", "validation accuracy", "training accuracy", "map score",
    ],
    "genai": [
        "gpt", "llm", "openai api", "anthropic", "gemini",
        "chatbot", "chat completion", "conversational ai", "ai assistant",
        "prompt engineering", "prompt template", "system prompt",
        "tool calling", "function calling", "document qa",
        "rag", "vector store", "retrieval augmented", "semantic search",
        "langchain", "llamaindex",
        "lora", "qlora", "context window",
        "chain of thought", "few shot", "zero shot", "reasoning model", "token budget",
        "llama", "mistral", "vllm", "kv cache", "speculative decoding",
        "llm inference", "transformer inference",
    ],
    "agentic_ai": [
        "agentic", "multi-agent", "autonomous agent", "autonomous llm",
        "mcp", "model context protocol", "langchain agent", "adk",
        "agent development kit", "agent orchestration", "llm orchestration",
        "agent loop", "plan and execute", "rag agent", "agentic ai",
        "agent planning", "agent reflection", "goal directed agent",
        "copilot", "ai copilot", "copilot system",
        "agent executor", "tool use", "tool calling agent", "tool router",
        "workflow engine", "reasoning loop",
        "multi-step workflow", "task decomposition",
        "memory retrieval", "agent memory", "planning agent",
        "planner", "executor agent", "autonomous assistant",
        "agent pipeline", "agent chain",
        "voice agent", "voice ai", "speech agent",
        "ai agents", "agent sdk", "agent framework",
    ],
    "frontend": [
        "react", "nextjs", "vue", "angular",
        "figma", "react native", "flutter", "svelte",
        "redux", "vite", "webpack", "sass", "scss",
        "dom", "jsx", "tsx", "browser api", "web component",
        "responsive ui", "responsive design", "user interface",
        "browser extension", "component system", "component library",
        "animation", "transition", "interaction",
        "user experience", "ux", "dashboard",
        "client-side", "realtime ui", "state management",
        "visualization", "chart", "data visualization",
        "drag drop", "drag and drop", "dnd",
        "canvas", "canvas interaction",
        "rich text editor", "code editor", "editor",
        "accessibility", "a11y", "aria",
    ],
    "backend": [
        "backend", "rest", "graphql", "fastapi",
        "express", "django", "flask",
        "spring boot", "springboot", "spring security", "spring data",
        "gin", "actix", "axum",
        "jpa", "hibernate", "servlet", "restcontroller",
        "microservice", "webhook", "middleware", "endpoint",
        "service layer", "repository pattern",
        "websocket", "pubsub", "event bus", "notification service",
        "background worker", "retry queue", "async workflow",
        "orchestration", "synchronization", "request coordination",
        "rate limiting", "rate limiter", "throttling",
        "circuit breaker",
        "retry strategy", "retry logic", "exponential backoff",
        "idempotency", "idempotent",
        "distributed cache", "cache invalidation", "cache layer",
        "request batching", "batch processing",
        "api composition", "api aggregation", "api gateway pattern",
        "service discovery", "service registry",
    ],
    "devops": [
        "docker", "kubernetes", "k8s", "aws", "gcp",
        "terraform", "helm", "ansible", "jenkins", "github actions", "gitlab ci",
        "serverless", "cloudflare", "vercel", "netlify", "nginx",
        "azure", "heroku",
        "ci/cd pipeline", "cd pipeline", "release pipeline", "build pipeline",
        "infrastructure as code", "gitops", "iac",
        "sre", "site reliability",
        "observability", "infrastructure monitoring",
        "container orchestration",
        "canary deployment", "blue-green deployment", "rolling deployment",
        "bash", "shell script", "shell scripting", "linux", "unix",
        "docker compose", "docker-compose", "multi-container", "multi-service deployment",
        "load balancer", "load balancing", "reverse proxy", "proxy server",
        "health check", "readiness probe", "liveness probe", "graceful shutdown",
        "cloud native", "12-factor", "twelve-factor", "immutable infrastructure",
    ],
    "database": [
        "mongo", "mysql", "postgres", "redis", "firebase", "supabase",
        "cassandra", "elasticsearch", "sqlite", "dynamodb", "clickhouse",
        "orm", "database schema", "database design", "database management",
        "sql query", "database query", "query optimization",
        "data migration", "schema migration", "db migration",
        "relational database", "nosql database", "document store",
        "indexing strategy", "sharding", "replication",
        "crud", "crud operations", "data modeling",
    ],
    "systems": [
        # Classic OS / low-level
        "concurrency", "multithreading", "memory management", "operating system",
        "linux kernel", "file system", "process scheduling", "ipc", "shared memory",
        "deadlock", "mutex", "allocator", "fork", "signals", "atomic", "lock free",
        "kernel module", "syscall", "mmap", "page fault", "virtual memory",
        "spinlock", "futex", "epoll", "ptrace",
        "heap allocator", "garbage collector runtime",
        # Modern systems engineering — Linux, Go, C++, performance
        "golang", "goroutine", "channel", "go runtime", "go scheduler",
        "systems engineering", "systems programmer", "systems programming",
        "linux engineering", "linux fundamentals", "linux systems",
        "c/c++", "performance engineering", "high performance systems",
        "low latency", "zero copy", "zero-copy", "memory safe",
        "async io", "io_uring", "io multiplexing", "event loop",
        "thread pool", "work stealing", "coroutine", "cooperative scheduling",
        "posix", "system calls", "process management", "process lifecycle",
        "runtime engineering", "runtime scheduler",
        "distributed runtime", "distributed systems engineering",
        "platform engineering systems", "infrastructure engineering",
        "network programming", "high throughput", "throughput optimization",
    ],
    "mlops": [
        "mlops", "mlflow", "kubeflow", "model serving",
        "model deployment", "inference", "ml pipeline", "ml data pipeline",
        "feature store", "experiment tracking", "bentoml", "triton",
        "model monitoring", "continuous training", "model registry",
        "model versioning", "data drift", "prediction drift",
    ],
    "data_engineering": [
        # Core ETL / pipeline
        "etl", "extract transform load",
        "data pipeline", "data engineering", "data engineer",
        "analytics engineering", "data analytics pipeline",
        "data orchestration", "pipeline orchestration",
        "batch processing", "batch pipeline", "data ingestion",
        # Processing engines
        "spark", "apache spark", "pyspark", "hadoop", "hive", "flink", "apache flink",
        # Workflow orchestration
        "airflow", "prefect", "dagster", "luigi",
        # Data warehouses
        "data warehouse", "redshift", "bigquery", "snowflake", "databricks",
        "data mart", "olap", "dimensional modeling", "star schema", "fact table",
        # Data lakes / lakehouses
        "data lake", "delta lake", "lakehouse", "apache iceberg", "apache hudi",
        # Transformation
        "dbt", "data build tool", "sql transformation", "data transformation",
        # Data quality / governance
        "data quality", "data lineage", "data catalog", "data governance",
        "data mesh", "data contract",
        # Cloud data platforms
        "cloud data platform", "data platform", "analytics platform",
        "aws glue", "azure data factory", "google dataflow",
        # Streaming
        "kafka streams", "data streaming", "kinesis", "event streaming pipeline",
        # Storage formats
        "parquet", "avro", "orc",
        # SQL analytics
        "sql analytics", "analytical sql", "window functions",
        "business intelligence", "bi dashboard",
    ],
    "algorithms": [
        "dsa", "leetcode", "codeforces",
        "binary tree", "avl tree", "segment tree", "trie", "heap",
        "directed graph", "adjacency list", "topological sort",
        "dynamic programming", "binary search",
        "hackerrank",
        "competitive programming", "greedy", "backtracking",
        "two pointers", "sliding window",
        "atcoder", "advent of code", "aoc", "icpc", "olympiad",
    ],
    "cybersecurity": [
        "malware", "reverse engineering", "reversing", "exploit", "exploitation",
        "payload", "shellcode", "injection", "evasion", "bypass", "rootkit",
        "ransomware", "trojan", "backdoor", "c2", "command and control",
        "red team", "redteam", "pentest", "penetration testing", "ctf",
        "capture the flag", "vulnerability", "zero day", "privilege escalation",
        "lateral movement", "persistence mechanism",
        "obfuscation", "antivirus",
        "edr", "endpoint detection", "windows internals",
        "disassembler", "ghidra", "ida pro", "radare",
        "steganography", "cryptography challenge", "forensics",
        "osint", "threat intelligence", "blue team", "incident response",
        "binary analysis", "disassembly",
        "assembly", "static analysis", "dynamic analysis", "binary exploitation",
        "arp spoofing", "arp poisoning", "man in the middle",
        "network attack", "packet sniffing", "intrusion detection",
        "ids", "ips", "honeypot",
        "encryption", "aes", "rsa", "tls", "ssl", "hmac", "sha",
        "vault", "secret management", "secure storage", "key management",
        "credential", "password hashing", "token security", "api key security",
        "access control", "rbac", "iam", "authentication security",
        "zero trust", "principle of least privilege", "secure coding",
    ],
    "blockchain": [
        "smart contract", "solidity", "ethereum", "web3",
        "defi", "nft", "dapp",
        "polygon", "chainlink", "hardhat", "truffle",
        "metamask", "evm", "ganache", "solana",
        "zero knowledge", "zkp", "zk-snark", "layer 2", "dao",
    ],
    "embedded": [
        "embedded", "firmware", "rtos", "microcontroller", "arduino",
        "raspberry pi", "esp32", "stm32", "fpga", "vhdl", "verilog",
        "vlsi", "rtl", "synthesis", "iot", "internet of things",
        "sensor", "actuator", "uart", "spi", "i2c", "gpio",
        "bare metal", "interrupt", "bootloader",
        "mqtt", "zigbee", "lora", "bluetooth low energy", "rf", "pwm",
        "pcb", "schematic", "kicad",
        "real-time embedded", "real time operating",
    ],
    "data_science": [
        "data science", "exploratory data analysis",
        "statistics", "data cleaning", "eda",
        "pandas", "numpy", "matplotlib", "seaborn",
        "hypothesis testing", "correlation analysis", "statistical significance",
        "feature distribution", "regression analysis", "scipy",
    ],
    "networking": [
        "network protocol", "tcp ip", "dns", "dhcp",
        "vpn", "routing", "bgp", "nat",
        "icmp", "ethernet", "udp",
        "tcp handshake",
        "flow control", "congestion control",
        "arp", "ospf", "link state advertisement",
        "wire protocol", "network stack",
        "packet forwarding", "routing table", "autonomous system",
    ],
    "distributed_systems": [
        "raft", "paxos", "consensus algorithm",
        "leader election", "quorum", "replication",
        "distributed storage", "consistent hashing", "sharding",
        "etcd", "zookeeper",
        "gossip protocol",
        "fault tolerant", "partition tolerance", "cap theorem",
        "eventual consistency",
        "mapreduce", "distributed hash table", "distributed file system",
        "linearizability", "distributed transaction",
        "chunkserver", "chunk server", "chunk replication",
        "master node", "worker node", "cluster coordinator",
        "heartbeat", "node failure", "failure recovery",
        "gfs", "hdfs", "distributed log",
        "replicated state machine", "distributed key value",
        "event driven architecture", "event-driven architecture",
        "message queue", "distributed queue",
        "pubsub architecture", "pub sub",
        "realtime synchronization", "distributed workflow",
        "task orchestration", "stream processing",
        "event streaming", "asynchronous coordination",
        "distributed messaging", "worker coordination",
    ],
}

BUNDLED_OVERLAP_DAMPENING = {
    "systems":             {"networking": 0.82, "embedded": 0.85, "distributed_systems": 0.85},
    "networking":          {"systems": 0.88, "cybersecurity": 0.85},
    "embedded":            {"systems": 0.88},
    "ai_ml":               {"data_science": 0.88, "mlops": 0.78, "genai": 0.72, "backend": 0.92, "devops": 0.82},
    "data_science":        {"ai_ml": 0.83},
    "genai":               {"ai_ml": 0.82, "backend": 0.90},
    "agentic_ai":          {"genai": 0.85, "backend": 0.90},
    "frontend":            {"backend": 0.93, "systems": 0.85},
    "backend":             {"frontend": 0.88, "distributed_systems": 0.86, "cybersecurity": 0.84, "ai_ml": 0.88},
    "devops":              {"ai_ml": 0.86, "distributed_systems": 0.80},
    "distributed_systems": {"backend": 0.90, "systems": 0.83, "devops": 0.83},
    "cybersecurity":       {"networking": 0.82, "backend": 0.88},
    "algorithms":          {"systems": 0.90, "backend": 0.92, "ai_ml": 0.92, "frontend": 0.90},
}

DOMAIN_LIST = [
    "frontend", "backend", "devops", "database", "systems",
    "ai_ml", "genai", "agentic_ai", "mlops", "data_science",
    "data_engineering",
    "algorithms", "cybersecurity", "blockchain", "embedded",
    "networking", "distributed_systems",
]
